# Trajectory Analysis across models for Suo et. al.

In [1]:
0

0

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import sys
working_directory = "/home/icb/kemal.inecik/work/codes/sctram"
sys.path.append(working_directory)

import logging
import subprocess
import gc
import os
import time
import numpy as np
import pandas as pd
import networkx as nx
import scanpy as sc
import anndata as ad

sc.settings.verbose = 3

In [4]:
from sctram.api._lower_level import TrajectoryEvaluationAPI
from sctram.input import InputTrajectories
from sctram.generate.real import sc_suo_developmental_complete

2025-03-01 20:17:53.937 | INFO     | sctram.api._defaults_read:load_default_metrics:23 - Loaded default metrics from /home/icb/kemal.inecik/work/codes/sctram/sctram/api/_defaults.yaml
2025-03-01 20:17:53.938 | INFO     | sctram.api._defaults_read:load_default_metrics:79 - Default metrics YAML structure validated successfully.

In [5]:
# Important to have consistent figures across platforms

%matplotlib inline
%config InlineBackend.figure_format='retina'

import pickle

from networkx.drawing.nx_agraph import graphviz_layout
from matplotlib import gridspec
import matplotlib.pyplot as plt
import seaborn as sns
import colorcet as cc
from adjustText import adjust_text  
import matplotlib.patheffects as path_effects

_rcparams_path = os.path.join(working_directory, "reproducibility/figure_rcparams/rcparams.pickle")
with open(_rcparams_path, "rb") as file:
    _rcparams = pickle.load(file)
plt.rcParams.update(_rcparams)

In [6]:
dataset_dir = "/home/icb/kemal.inecik/lustre_workspace/temp_sctram_data"
helpers_directory = os.path.join(os.getcwd(), "helper")
logs_directory = os.path.join(os.getcwd(), "logs")
adata_suo_complete = sc_suo_developmental_complete(dataset_dir=dataset_dir)

2025-03-01 20:17:59.953 | WARNING  | sctram.generate.real._download:download_dataset:105 - File PosixPath('/home/icb/kemal.inecik/lustre_workspace/temp_sctram_data/suo_developmental_complete.h5ad') already exists. Skipping download.

In [7]:
input_trajectories_path = os.path.join(dataset_dir, f"adata_suo_input_haematopoeitic_lineage.pkl")
with open(input_trajectories_path, "rb") as _file:
    lit = pickle.load(_file)

In [9]:
def plot_obsms(lin, plot_obs, adata, label_on_data=False, n_cols=4, subplot_size=(5, 4), prevent_bottom_legend=False):
    # Collect all categories and their global counts for consistent coloring
    lin = lin.replace('_lineage', '').lower()
    global_counts = {}
    
    # First pass to get all categories and their global counts
    for use_rep in adata[lin]:
        adata_obj = adata[lin][use_rep]
        counts = adata_obj.obs[plot_obs].astype(str).value_counts().to_dict()
        for cat, count in counts.items():
            global_counts[cat] = global_counts.get(cat, 0) + count
        break  # as all the reps have the same anndata.obs
    
    # Sort categories by global abundance descending
    unique_lvl = sorted(global_counts.keys(), key=lambda x: -global_counts[x])
    
    # Create color mapping based on global abundance
    n_cats = len(unique_lvl)
    palette = sns.color_palette(cc.glasbey_category10, n_cats)
    lvl_to_color = {cat: palette[i] for i, cat in enumerate(unique_lvl)}
    
    # Plotting parameters
    n_cols = n_cols
    subplot_size = subplot_size
    legend_ncol = 4
    
    use_reps = list(adata[lin].keys())
    if not use_reps:
        raise ValueError(f"no obsm for {lin!r}")
        
    n_subplots = len(use_reps)
    n_rows = int(np.ceil(n_subplots / n_cols))
    n_datapoints = len(next(iter(adata[lin].values())))  # Get count from first adata_obj
    
    # Dynamic point size calculation
    base_size = 1e5
    s = base_size / n_datapoints
    
    # Figure setup
    fig_width = subplot_size[0] * n_cols
    fig_height = subplot_size[1] * n_rows + 2
    fig = plt.figure(figsize=(fig_width, fig_height))
    gs = gridspec.GridSpec(n_rows, n_cols, figure=fig)
    
    # Plot each use_rep with local abundance ordering
    for idx, use_rep in enumerate(use_reps):
        ax = fig.add_subplot(gs[idx // n_cols, idx % n_cols])
        adata_obj = adata[lin][use_rep]
        umap_coords = adata_obj.obsm['X_umap']
        
        # Get local counts for layering order
        local_counts = adata_obj.obs[plot_obs].astype(str).value_counts().sort_values(ascending=False)
        sorted_cats = local_counts.index.tolist()
        
        # Plot each category in abundance order (large to small)
        for cat in sorted_cats:
            mask = adata_obj.obs[plot_obs].astype(str) == cat
            ax.scatter(
                umap_coords[mask, 0],
                umap_coords[mask, 1],
                s=s,
                c=[lvl_to_color[cat]],
                alpha=0.4,
                linewidth=s*0.3,
                # rasterized=True,
                edgecolor='none'
            )
        
        # Add labels on data if enabled
        if label_on_data:
            texts = []
            centroid_info = []  # Stores (centroid, color) for each label
            
            for cat in sorted_cats:
                mask = adata_obj.obs[plot_obs].astype(str) == cat
                coords = umap_coords[mask]
                if len(coords) == 0:
                    continue
                
                # Compute centroid with outlier removal
                initial_centroid = np.mean(coords, axis=0)
                distances = np.linalg.norm(coords - initial_centroid, axis=1)
                std = np.std(distances)
                if std == 0:
                    final_centroid = initial_centroid
                else:
                    threshold = 3.0 * std
                    filtered = distances <= threshold
                    filtered_coords = coords[filtered]
                    final_centroid = np.mean(filtered_coords, axis=0) if len(filtered_coords) > 0 else initial_centroid
                
                # Plot enlarged centroid point
                ax.scatter(
                    final_centroid[0], final_centroid[1],
                    s=30*s,  # 10x normal size
                    c=[lvl_to_color[cat]],
                    alpha=1.0,
                    edgecolor='white',
                    linewidth=s*1,
                    zorder=5
                )
                
                # Create squeezed text using LaTeX \scalebox
                txt = ax.text(
                    final_centroid[0], final_centroid[1],
                    cat,
                    fontsize=6,
                    weight='bold',  # Make text bold
                    ha='center',
                    va='center',
                    color="black", #lvl_to_color[cat],
                    zorder=6
                )
                # Add a white outline effect around the text
                txt.set_path_effects([
                    path_effects.Stroke(linewidth=0.5, foreground='white'),
                    path_effects.Normal()
                ])
                
                texts.append(txt)
                centroid_info.append((final_centroid, lvl_to_color[cat]))
            
            # Adjust text positions without automatic arrows
            if texts:
                adjust_text(
                    texts, 
                    ax=ax,
                    force_text=(0.3, 0.3),   # Increase these values for stronger text movement
                    force_points=(1.8, 1.8),
                    lim=500
                )
                
                # Add manual colored arrows
                for txt, (centroid, color) in zip(texts, centroid_info):
                    # Get the text bounding box in data coordinates
                    renderer = fig.canvas.get_renderer()
                    bbox = txt.get_window_extent(renderer=renderer)
                    bbox_data = ax.transData.inverted().transform(bbox)
                    
                    # Calculate the center of the text bounding box
                    text_center = [
                        (bbox_data[0, 0] + bbox_data[1, 0]) / 2,  # x-center
                        (bbox_data[0, 1] + bbox_data[1, 1]) / 2   # y-center
                    ]
                    
                    # Draw arrow from centroid to text center
                    ax.annotate(
                        '',
                        xy=centroid,  # Arrow points to text center
                        xytext=text_center,  # Arrow starts at centroid
                        arrowprops=dict(
                            arrowstyle='->',
                            color="black", #color,
                            lw=0.5,
                            alpha=1,
                            connectionstyle="arc3,rad=0.15"  # Adjust curvature as needed
                        ),
                        zorder=4
                    )
        
        # Subplot formatting
        ax.set_title(use_rep, fontsize=10)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.spines[:].set_visible(False)

    if not label_on_data and not prevent_bottom_legend:
        # Create unified legend only if labels are not on data
        legend_handles = [
            plt.Line2D([0], [0], 
             marker='o', 
             color='w', 
             markerfacecolor=lvl_to_color[cat], 
             markersize=10,
             label=f"{cat} ({global_counts[cat]:,})")
            for cat in unique_lvl
        ]
        
        fig.legend(
            handles=legend_handles,
            loc='lower center',
            ncol=legend_ncol,
            bbox_to_anchor=(0.5, -0.05),
            frameon=False,
            fontsize=10,
            handletextpad=0.1
        )

    # Final layout adjustments
    plt.tight_layout(rect=[0, 0.1, 1, 0.95])
    fig.suptitle(f"{lin} - {plot_obs}", y=0.98, fontsize=12)
    plt.show()

In [10]:
def plot_trajectory(
        graph,
        title,
        figsize=(12, 4),
        font_size=10,
        node_size=300,
        node_color='#8DA0CB',  # Modern muted blue
        cmap='viridis',
        color_nodes_by_position=False,
        edge_width=1,
        edge_color='gray',
        label_offset=25,
        title_y=1.02,
        layout_args="-Grankdir=LR -Gnodesep=1.0 -Granksep=2.5"
    ):
    fig = plt.figure(figsize=figsize)
    ax = fig.add_subplot(111)

    # Calculate hierarchical layout
    pos = graphviz_layout(graph, prog="dot", args=layout_args)

    # Calculate node colors using positional gradient
    if color_nodes_by_position:
        try:
            xs = [pos[node][0] for node in graph.nodes]
            min_x, max_x = min(xs), max(xs)
            if max_x != min_x:
                color_vals = [(x - min_x)/(max_x - min_x) for x in xs]
            else:  # Fallback if single column
                color_vals = [0.5]*len(xs)
            node_color = plt.get_cmap(cmap)(color_vals)
        except:
            print("Warning: Positional coloring failed. Using base color.")

    # Calculate label positions
    label_pos = {n: (x, y + label_offset) for n, (x, y) in pos.items()}

    # Draw network elements
    nx.draw_networkx_nodes(
        graph, pos, ax=ax,
        node_size=node_size,
        node_color=node_color,
        edgecolors='black',
        linewidths=0.8,
        alpha=1.0
    )

    nx.draw_networkx_edges(
        graph, pos, ax=ax,
        arrowstyle='-|>',
        arrowsize=15,
        edge_color=edge_color,
        width=edge_width,
        alpha=1.0,
        connectionstyle='arc3'
        # connectionstyle='arc3,rad=0.2'
    )

    nx.draw_networkx_labels(
        graph, label_pos, ax=ax,
        font_size=font_size,
        font_weight='normal',
        font_family=plt.rcParams['font.family'],
        alpha=1.0
    )

    # Add styled title
    fig.suptitle(
        title,
        y=title_y,
        fontsize=font_size + 2,
        fontweight='bold',
        color='#333333'
    )

    # Configure final layout
    plt.subplots_adjust(
        left=0.03,
        right=0.97,
        top=0.88 if title else 0.97,
        bottom=0.03
    )
    ax.set_axis_off()
    plt.show()

In [11]:
n_neighbors = 50
lineages = ["Haematopoeitic_lineage"]

In [12]:
adata_lineage = dict()
for lineage in lineages:
    lineage_part = lineage.replace('_lineage', '').lower()
    adata_lineage[lineage_part] = dict()
    for use_rep in adata_suo_complete.obsm.keys():
        output_file = os.path.join(dataset_dir, f"adata_suo_{lineage_part}_umap_{use_rep}.h5ad")
        if not os.path.exists(output_file):
            print(f"! - Not exists: {lineage!r} with {use_rep!r}")
        else:
            print(f"- Loaded: {lineage!r} with {use_rep!r}")
            adata_lineage[lineage_part][use_rep] = ad.read_h5ad(output_file)

- Loaded: 'Haematopoeitic_lineage' with 'Unintegrated'
- Loaded: 'Haematopoeitic_lineage' with 'X_pca'
- Loaded: 'Haematopoeitic_lineage' with 'harmony'
- Loaded: 'Haematopoeitic_lineage' with 'invae'
- Loaded: 'Haematopoeitic_lineage' with 'scanvi'
- Loaded: 'Haematopoeitic_lineage' with 'scvi'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_1'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_2'

In [15]:
lineage = "Haematopoeitic_lineage"
stem_cells = 'Haematopoetic_progenitors'
lvl1_haematopoeitic = np.array(adata_suo_complete[adata_suo_complete.obs["LVL0"] == lineage].obs["LVL1"].unique())
groups = {f"stem_cells_and_{i.lower()}": [stem_cells, i] for ind, i in enumerate(lvl1_haematopoeitic) if i != stem_cells}

adata_groups = dict()
for g in groups.keys():
    lineage_part = lineage.replace('_lineage', '').lower()
    adata_groups[g] = dict()
    for use_rep in adata_suo_complete.obsm.keys():
        output_file = os.path.join(dataset_dir, f"adata_suo_{lineage_part}_umap_{use_rep}_{g}.h5ad")
        if not os.path.exists(output_file):
            print(f"! - Not exists: {lineage!r} with {use_rep!r} of group {g!r}")
        else:
            print(f"- Loaded: {lineage!r} with {use_rep!r} of group {g!r}")
            adata_groups[g][use_rep] = ad.read_h5ad(output_file)

- Loaded: 'Haematopoeitic_lineage' with 'Unintegrated' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'X_pca' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'harmony' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'invae' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'scanvi' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'scvi' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_1' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_2' of group 'stem_cells_and_myeloid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'Unintegrated' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'X_pca' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'harmony' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'invae' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'scanvi' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'scvi' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_1' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_2' of group 'stem_cells_and_mem'
- Loaded: 'Haematopoeitic_lineage' with 'Unintegrated' of group 'stem_cells_and_lymphoid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'X_pca' of group 'stem_cells_and_lymphoid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'harmony' of group 'stem_cells_and_lymphoid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'invae' of group 'stem_cells_and_lymphoid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'scanvi' of group 'stem_cells_and_lymphoid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'scvi' of group 'stem_cells_and_lymphoid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_1' of group 'stem_cells_and_lymphoid_differentiated_cells'
- Loaded: 'Haematopoeitic_lineage' with 'tardis_2' of group 'stem_cells_and_lymphoid_differentiated_cells'

In [25]:
df = pd.DataFrame()
lineage = "Haematopoeitic_lineage"
for trajectory in sorted(lit.graph["trajectories"]):
    lineage_part = lineage.replace("_lineage", "").lower()
    for use_rep in adata_suo_complete.obsm.keys():
        if use_rep == "Unintegrated":
            continue
        output_file = os.path.join(dataset_dir, f"_metric_adata_suo_{lineage_part}_{use_rep}_{trajectory}.pickle")
        df_trajectory_obsm = pd.read_pickle(output_file)
        df_trajectory_obsm["representation"] = use_rep
        df_trajectory_obsm["trajectory"] = trajectory
        df = pd.concat([df, df_trajectory_obsm])
df.reset_index(drop=True, inplace=True)
df['score'] = pd.to_numeric(df['score'], errors='raise')
df.sort_values(by=["trajectory", "path", "metric", "representation"], inplace=True, ignore_index=True)
df = df[["trajectory", "path", "metric", "representation", "score"]]

In [32]:
df["trajectory"].unique()

array(['alternative_myeloid', 'b_cell_specialization', 'b_cells', 'cd4',
       'complete_stem_trajectory', 'dendritic', 'early_b_cells',
       'early_lymphoid', 'early_stem_trajectory', 'elp_branching',
       'erythroid', 'erythroid_megakaryocyte', 'gmp_branching',
       'granulocyte_macrophage', 'granulocyte_mast',
       'granulocyte_monocytes', 'haematopoeitic_lineage', 'icl_nk',
       'macrophage_specialization', 'megakaryocyte', 'neutrophil',
       'stem_cells_and_lymphoid_differentiated_cells',
       'stem_cells_and_mem',
       'stem_cells_and_myeloid_differentiated_cells', 't_cell_mid',
       't_cell_nkt', 'tissue_macrophages'], dtype=object)

In [26]:
1

1

## Data loading

In [31]:
df_trajectory = df[df["trajectory"] == "b_cells"]
df_trajectory = df_trajectory.pivot(index=['path', 'metric'], columns='representation', values='score')
df_trajectory

representation                                      X_pca      harmony  \
path       metric
adjacency  accuracy                              0.867769     0.801653
           average_shortest_path_difference      3.519108     3.481756
           clustering_coeff_diff                 0.123038     0.203349
           f1_score                              0.692308     0.600000
           frobenius                             3.752799     3.968247
           gdv_similarity                        0.899926     0.810600
           gin_gnn_similarity                    0.956072     0.945270
           graph_edit_distance                   8.000000    12.000000
           hamming_distance                     16.000000    24.000000
           jaccard_similarity                    0.529412     0.428571
           l1_norm                              20.123344    25.450836
           laplacian_spectral_emd                0.015372     0.027926
           mantel_correlation                    0.058396     0.195056
           maximum_common_subgraph_distance      8.000000    12.000000
           permutation_marginalized_ssim         0.539210     0.486602
           persistence_diagram_distance          5.818456     1.895933
           precision                             0.562500     0.450000
           random_walk_kernel_distance           0.854726     0.925401
           recall                                0.900000     0.900000
           spectral_distance                     1.948751     2.163900
           weisfeiler_lehman_distance            0.593185     0.810701
embedding  branch_silhouette_score                    NaN     0.011091
           directionality_preservation          -0.219679    -0.304184
           embedding_distance_correlation        0.721571     0.641080
           gearys_c_embedding                    0.568228     0.609445
           graph_based_trustworthiness           0.932537     0.880163
           morans_i_embedding                    0.460522     0.363984
           neighborhood_preservation_score       0.351612     0.305069
           normalized_mean_curvature             0.033321     0.043114
           sammons_stress                        0.155161     0.172991
           trajectory_cardinality_validation     0.563201     0.610687
           wasserstein_distance_embedding        9.460959     8.836190
pseudotime cdf_cramer_von_mises               6759.155616  8536.733011
           cdf_kolmogorov_smirnov                0.757682     0.889833
           concordance_index                     0.917067     0.798782
           dtw_distance                          0.062450     0.074071
           gearys_c_pseudotime                   0.210817     0.593367
           kendall_correlation                   0.768770     0.550738
           mae                                   0.268697     0.405367
           morans_i_pseudotime                   0.734856     0.400879
           mse                                   0.098798     0.189873
           mutual_information_kde                0.201041    -0.057300
           normalized_mutual_information         0.346757     0.166154
           pearson_correlation                   0.672096     0.256520
           r_squared                            -2.451438    -9.680343
           r_squared_with_spline                 0.816168     0.455389
           spearman_correlation                  0.910198     0.697645
           wasserstein_distance_pseudotime       0.303382     0.566860

representation                                      invae       scanvi  \
path       metric
adjacency  accuracy                              0.917355     0.867769
           average_shortest_path_difference      3.519509     3.523224
           clustering_coeff_diff                 0.105393     0.050193
           f1_score                              0.782609     0.555556
           frobenius                             3.506338     3.644133
           gdv_similarity                        0.886667     0.892000
           gin_gnn_similarity                    0.992697     0.999379
           graph_edit_distance                   5.000000     8.000000
           hamming_distance                     10.000000    16.000000
           jaccard_similarity                    0.642857     0.384615
           l1_norm                              18.161655    17.649683
           laplacian_spectral_emd                0.015831     0.006550
           mantel_correlation                    0.027500     0.005770
           maximum_common_subgraph_distance      5.000000     8.000000
           permutation_marginalized_ssim         0.572532     0.441650
           persistence_diagram_distance          6.644425    18.227735
           precision                             0.692308     0.625000
           random_walk_kernel_distance           0.624069     0.385656
           recall                                0.900000     0.500000
           spectral_distance                     1.579184     1.333469
           weisfeiler_lehman_distance            0.569868     0.510224
embedding  branch_silhouette_score                    NaN          NaN
           directionality_preservation           0.084608    -0.067710
           embedding_distance_correlation        0.850524     0.804691
           gearys_c_embedding                    0.480590     0.588714
           graph_based_trustworthiness           0.935637     0.968451
           morans_i_embedding                    0.499900     0.438772
           neighborhood_preservation_score       0.333496     0.349189
           normalized_mean_curvature             0.454695     0.276632
           sammons_stress                        0.145744     0.113587
           trajectory_cardinality_validation     0.591822     0.563864
           wasserstein_distance_embedding        9.504878     9.161482
pseudotime cdf_cramer_von_mises               6031.974409  6018.764970
           cdf_kolmogorov_smirnov                0.711619     0.707430
           concordance_index                     0.912061     0.952410
           dtw_distance                          0.067726     0.062963
           gearys_c_pseudotime                   0.305533     0.136470
           kendall_correlation                   0.759542     0.833916
           mae                                   0.163816     0.239887
           morans_i_pseudotime                   0.638791     0.820213
           mse                                   0.038194     0.086836
           mutual_information_kde                0.191347     0.347427
           normalized_mutual_information         0.281521     0.410201
           pearson_correlation                   0.790693     0.702607
           r_squared                            -0.275755    -1.754398
           r_squared_with_spline                 0.757333     0.926939
           spearman_correlation                  0.902794     0.943347
           wasserstein_distance_pseudotime       0.172707     0.257134

representation                                       scvi     tardis_1  \
path       metric
adjacency  accuracy                              0.900826     0.867769
           average_shortest_path_difference      3.520389     3.518697
           clustering_coeff_diff                 0.087508     0.085116
           f1_score                              0.727273     0.600000
           frobenius                             3.683601     3.582148
           gdv_similarity                        0.920618     0.899025
           gin_gnn_similarity                    0.996532     0.999229
           graph_edit_distance                   6.000000     8.000000
           hamming_distance                     12.000000    16.000000
           jaccard_similarity                    0.571429     0.428571
           l1_norm                              19.157487    18.270390
           laplacian_spectral_emd                0.010860     0.009122
           mantel_correlation                   -0.167044    -0.076547
           maximum_common_subgraph_distance      6.000000     8.000000
           permutation_marginalized_ssim         0.510536     0.520856
           persistence_diagram_distance          7.930528     9.328984
           precision                             0.666667     0.600000
           random_walk_kernel_distance           0.449150     0.399471
           recall                                0.800000     0.600000
           spectral_distance                     1.266865     1.200724
           weisfeiler_lehman_distance            0.499505     0.521277
embedding  branch_silhouette_score               0.087303     0.013567
           directionality_preservation          -0.000579    -0.354449
           embedding_distance_correlation        0.668032     0.561136
           gearys_c_embedding                    0.689759     0.762744
           graph_based_trustworthiness           0.931758     0.929760
           morans_i_embedding                    0.204482     0.264169
           neighborhood_preservation_score       0.325762     0.319719
           normalized_mean_curvature             0.388207     0.237310
           sammons_stress                        0.191886     0.229526
           trajectory_cardinality_validation     0.664720     0.597572
           wasserstein_distance_embedding        9.126541     9.220127
pseudotime cdf_cramer_von_mises               5003.612928  4908.965837
           cdf_kolmogorov_smirnov                0.679300     0.680309
           concordance_index                     0.866456     0.919918
           dtw_distance                          0.036488     0.040647
           gearys_c_pseudotime                   0.384829     0.351122
           kendall_correlation                   0.675479     0.774025
           mae                                   0.085379     0.089106
           morans_i_pseudotime                   0.457541     0.577060
           mse                                   0.011252     0.011994
           mutual_information_kde                0.193304     0.336344
           normalized_mutual_information         0.233697     0.254108
           pearson_correlation                   0.901219     0.918687
           r_squared                             0.618906     0.261776
           r_squared_with_spline                 0.859582     0.877707
           spearman_correlation                  0.837317     0.908823
           wasserstein_distance_pseudotime       0.093462     0.143348

representation                                   tardis_2
path       metric
adjacency  accuracy                              0.867769
           average_shortest_path_difference      3.520148
           clustering_coeff_diff                 0.080992
           f1_score                              0.600000
           frobenius                             3.750947
           gdv_similarity                        0.899025
           gin_gnn_similarity                    0.999220
           graph_edit_distance                   8.000000
           hamming_distance                     16.000000
           jaccard_similarity                    0.428571
           l1_norm                              18.694525
           laplacian_spectral_emd                0.008719
           mantel_correlation                   -0.021620
           maximum_common_subgraph_distance      8.000000
           permutation_marginalized_ssim         0.504286
           persistence_diagram_distance          9.057975
           precision                             0.600000
           random_walk_kernel_distance           0.460875
           recall                                0.600000
           spectral_distance                     1.231411
           weisfeiler_lehman_distance            0.521277
embedding  branch_silhouette_score               0.031760
           directionality_preservation           0.290174
           embedding_distance_correlation        0.744396
           gearys_c_embedding                    0.697596
           graph_based_trustworthiness           0.939098
           morans_i_embedding                    0.297999
           neighborhood_preservation_score       0.334744
           normalized_mean_curvature             0.247156
           sammons_stress                        0.163195
           trajectory_cardinality_validation     0.603173
           wasserstein_distance_embedding        9.229324
pseudotime cdf_cramer_von_mises               5525.980834
           cdf_kolmogorov_smirnov                0.683795
           concordance_index                     0.950872
           dtw_distance                          0.055632
           gearys_c_pseudotime                   0.244022
           kendall_correlation                   0.831081
           mae                                   0.125488
           morans_i_pseudotime                   0.653353
           mse                                   0.023039
           mutual_information_kde                0.373612
           normalized_mutual_information         0.316005
           pearson_correlation                   0.874492
           r_squared                            -0.178239
           r_squared_with_spline                 0.910970
           spearman_correlation                  0.942312
           wasserstein_distance_pseudotime       0.179289

In [33]:
def min_max_normalize(row):
    min_val = row.min()
    max_val = row.max()
    if max_val == min_val:
        return pd.Series(1, index=row.index) 
    else:
        return (row - min_val) / (max_val - min_val)

df_trajectory = df_trajectory.apply(min_max_normalize, axis=1)
df_trajectory

representation                                   X_pca   harmony     invae  \
path       metric
adjacency  accuracy                           0.571429  0.000000  1.000000
           average_shortest_path_difference   0.900737  0.000000  0.910416
           clustering_coeff_diff              0.475622  1.000000  0.360414
           f1_score                           0.602291  0.195745  1.000000
           frobenius                          0.533571  1.000000  0.000000
           gdv_similarity                     0.811918  0.000000  0.691400
           gin_gnn_similarity                 0.199622  0.000000  0.876505
           graph_edit_distance                0.428571  1.000000  0.000000
           hamming_distance                   0.428571  1.000000  0.000000
           jaccard_similarity                 0.560701  0.170213  1.000000
           l1_norm                            0.317089  1.000000  0.065628
           laplacian_spectral_emd             0.412728  1.000000  0.434184
           mantel_correlation                 0.622592  1.000000  0.537267
           maximum_common_subgraph_distance   0.428571  1.000000  0.000000
           permutation_marginalized_ssim      0.745404  0.343460  1.000000
           persistence_diagram_distance       0.240177  0.000000  0.290751
           precision                          0.464286  0.000000  1.000000
           random_walk_kernel_distance        0.869059  1.000000  0.441714
           recall                             1.000000  1.000000  1.000000
           spectral_distance                  0.776626  1.000000  0.392929
           weisfeiler_lehman_distance         0.301033  1.000000  0.226103
embedding  branch_silhouette_score                 NaN  0.000000       NaN
           directionality_preservation        0.209067  0.077976  0.681106
           embedding_distance_correlation     0.554392  0.276249  1.000000
           gearys_c_embedding                 0.310606  0.456685  0.000000
           graph_based_trustworthiness        0.593224  0.000000  0.628329
           morans_i_embedding                 0.866706  0.539921  1.000000
           neighborhood_preservation_score    1.000000  0.000000  0.610768
           normalized_mean_curvature          0.000000  0.023241  1.000000
           sammons_stress                     0.358587  0.512377  0.277366
           trajectory_cardinality_validation  0.000000  0.467758  0.281929
           wasserstein_distance_embedding     0.934321  0.000000  1.000000
pseudotime cdf_cramer_von_mises               0.510008  1.000000  0.309559
           cdf_kolmogorov_smirnov             0.372304  1.000000  0.153511
           concordance_index                  0.769947  0.000000  0.737361
           dtw_distance                       0.690785  1.000000  0.831165
           gearys_c_pseudotime                0.162721  1.000000  0.370026
           kendall_correlation                0.769947  0.000000  0.737361
           mae                                0.572890  1.000000  0.245124
           morans_i_pseudotime                0.796446  0.000000  0.567357
           mse                                0.490123  1.000000  0.150832
           mutual_information_kde             0.599521  0.000000  0.577025
           normalized_mutual_information      0.740032  0.000000  0.472724
           pearson_correlation                0.627601  0.000000  0.806705
           r_squared                          0.701887  0.000000  0.913133
           r_squared_with_spline              0.765092  0.000000  0.640321
           spearman_correlation               0.865084  0.000000  0.834953
           wasserstein_distance_pseudotime    0.443432  1.000000  0.167395

representation                                  scanvi      scvi  tardis_1  \
path       metric
adjacency  accuracy                           0.571429  0.857143  0.571429
           average_shortest_path_difference   1.000000  0.931635  0.890834
           clustering_coeff_diff              0.000000  0.243641  0.228019
           f1_score                           0.000000  0.756286  0.195745
           frobenius                          0.298316  0.383762  0.164124
           gdv_similarity                     0.739880  1.000000  0.803734
           gin_gnn_similarity                 1.000000  0.947389  0.997220
           graph_edit_distance                0.428571  0.142857  0.428571
           hamming_distance                   0.428571  0.142857  0.428571
           jaccard_similarity                 0.000000  0.723404  0.170213
           l1_norm                            0.000000  0.193280  0.079566
           laplacian_spectral_emd             0.000000  0.201654  0.120363
           mantel_correlation                 0.477257  0.000000  0.249924
           maximum_common_subgraph_distance   0.428571  0.142857  0.428571
           permutation_marginalized_ssim      0.000000  0.526320  0.605170
           persistence_diagram_distance       1.000000  0.369500  0.455127
           precision                          0.722222  0.894180  0.619048
           random_walk_kernel_distance        0.000000  0.117638  0.025596
           recall                             0.000000  0.750000  0.250000
           spectral_distance                  0.137819  0.068670  0.000000
           weisfeiler_lehman_distance         0.034443  0.000000  0.069960
embedding  branch_silhouette_score                 NaN  1.000000  0.032494
           directionality_preservation        0.444816  0.548956  0.000000
           embedding_distance_correlation     0.841620  0.369384  0.000000
           gearys_c_embedding                 0.383210  0.741330  1.000000
           graph_based_trustworthiness        1.000000  0.584394  0.561765
           morans_i_embedding                 0.793081  0.000000  0.202045
           neighborhood_preservation_score    0.947935  0.444589  0.314764
           normalized_mean_curvature          0.577423  0.842211  0.484104
           sammons_stress                     0.000000  0.675351  1.000000
           trajectory_cardinality_validation  0.006533  1.000000  0.338571
           wasserstein_distance_embedding     0.486464  0.434211  0.574165
pseudotime cdf_cramer_von_mises               0.305918  0.026090  0.000000
           cdf_kolmogorov_smirnov             0.133614  0.000000  0.004793
           concordance_index                  1.000000  0.440502  0.788503
           dtw_distance                       0.704443  0.000000  0.110643
           gearys_c_pseudotime                0.000000  0.543578  0.469804
           kendall_correlation                1.000000  0.440502  0.788503
           mae                                0.482855  0.000000  0.011648
           morans_i_pseudotime                1.000000  0.135122  0.420144
           mse                                0.423153  0.000000  0.004154
           mutual_information_kde             0.939234  0.581568  0.913514
           normalized_mutual_information      1.000000  0.276762  0.360398
           pearson_correlation                0.673678  0.973620  1.000000
           r_squared                          0.769565  1.000000  0.965325
           r_squared_with_spline              1.000000  0.857158  0.895596
           spearman_correlation               1.000000  0.568460  0.859488
           wasserstein_distance_pseudotime    0.345738  0.000000  0.105377

representation                                tardis_2
path       metric
adjacency  accuracy                           0.571429
           average_shortest_path_difference   0.925810
           clustering_coeff_diff              0.201092
           f1_score                           0.195745
           frobenius                          0.529560
           gdv_similarity                     0.803734
           gin_gnn_similarity                 0.997055
           graph_edit_distance                0.428571
           hamming_distance                   0.428571
           jaccard_similarity                 0.170213
           l1_norm                            0.133934
           laplacian_spectral_emd             0.101506
           mantel_correlation                 0.401614
           maximum_common_subgraph_distance   0.428571
           permutation_marginalized_ssim      0.478572
           persistence_diagram_distance       0.438533
           precision                          0.619048
           random_walk_kernel_distance        0.139361
           recall                             0.250000
           spectral_distance                  0.031860
           weisfeiler_lehman_distance         0.069960
embedding  branch_silhouette_score            0.271207
           directionality_preservation        1.000000
           embedding_distance_correlation     0.633266
           gearys_c_embedding                 0.769106
           graph_based_trustworthiness        0.667535
           morans_i_embedding                 0.316561
           neighborhood_preservation_score    0.637578
           normalized_mean_curvature          0.507471
           sammons_stress                     0.427885
           trajectory_cardinality_validation  0.393744
           wasserstein_distance_embedding     0.587919
pseudotime cdf_cramer_von_mises               0.170081
           cdf_kolmogorov_smirnov             0.021349
           concordance_index                  0.989988
           dtw_distance                       0.509378
           gearys_c_pseudotime                0.235396
           kendall_correlation                0.989988
           mae                                0.125344
           morans_i_pseudotime                0.602082
           mse                                0.065992
           mutual_information_kde             1.000000
           normalized_mutual_information      0.614024
           pearson_correlation                0.933257
           r_squared                          0.922602
           r_squared_with_spline              0.966135
           spearman_correlation               0.995788
           wasserstein_distance_pseudotime    0.181299

In [36]:
def find_max_min_models(row):
    max_models = row[row == row.max()].index.tolist()
    min_models = row[row == row.min()].index.tolist()
    if sorted(min_models) == sorted(max_models):
        max_models, min_models= "", ""
    return pd.Series([max_models, min_models], index=['Max_Scoring_Models', 'Min_Scoring_Models'])

df_trajectory_minmax = df_trajectory.apply(find_max_min_models, axis=1)

with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.float_format', '{:.6f}'.format):
    assert np.all(df_trajectory_minmax.index == df_trajectory.index)
    display(pd.concat([df_trajectory_minmax, df_trajectory], axis=1))

                                                   Max_Scoring_Models  \
path       metric
adjacency  accuracy                                           [invae]
           average_shortest_path_difference                  [scanvi]
           clustering_coeff_diff                            [harmony]
           f1_score                                           [invae]
           frobenius                                        [harmony]
           gdv_similarity                                      [scvi]
           gin_gnn_similarity                                [scanvi]
           graph_edit_distance                              [harmony]
           hamming_distance                                 [harmony]
           jaccard_similarity                                 [invae]
           l1_norm                                          [harmony]
           laplacian_spectral_emd                           [harmony]
           mantel_correlation                               [harmony]
           maximum_common_subgraph_distance                 [harmony]
           permutation_marginalized_ssim                      [invae]
           persistence_diagram_distance                      [scanvi]
           precision                                          [invae]
           random_walk_kernel_distance                      [harmony]
           recall                             [X_pca, harmony, invae]
           spectral_distance                                [harmony]
           weisfeiler_lehman_distance                       [harmony]
embedding  branch_silhouette_score                             [scvi]
           directionality_preservation                     [tardis_2]
           embedding_distance_correlation                     [invae]
           gearys_c_embedding                              [tardis_1]
           graph_based_trustworthiness                       [scanvi]
           morans_i_embedding                                 [invae]
           neighborhood_preservation_score                    [X_pca]
           normalized_mean_curvature                          [invae]
           sammons_stress                                  [tardis_1]
           trajectory_cardinality_validation                   [scvi]
           wasserstein_distance_embedding                     [invae]
pseudotime cdf_cramer_von_mises                             [harmony]
           cdf_kolmogorov_smirnov                           [harmony]
           concordance_index                                 [scanvi]
           dtw_distance                                     [harmony]
           gearys_c_pseudotime                              [harmony]
           kendall_correlation                               [scanvi]
           mae                                              [harmony]
           morans_i_pseudotime                               [scanvi]
           mse                                              [harmony]
           mutual_information_kde                          [tardis_2]
           normalized_mutual_information                     [scanvi]
           pearson_correlation                             [tardis_1]
           r_squared                                           [scvi]
           r_squared_with_spline                             [scanvi]
           spearman_correlation                              [scanvi]
           wasserstein_distance_pseudotime                  [harmony]

                                             Min_Scoring_Models    X_pca  \
path       metric
adjacency  accuracy                                   [harmony] 0.571429
           average_shortest_path_difference           [harmony] 0.900737
           clustering_coeff_diff                       [scanvi] 0.475622
           f1_score                                    [scanvi] 0.602291
           frobenius                                    [invae] 0.533571
           gdv_similarity                             [harmony] 0.811918
           gin_gnn_similarity                         [harmony] 0.199622
           graph_edit_distance                          [invae] 0.428571
           hamming_distance                             [invae] 0.428571
           jaccard_similarity                          [scanvi] 0.560701
           l1_norm                                     [scanvi] 0.317089
           laplacian_spectral_emd                      [scanvi] 0.412728
           mantel_correlation                            [scvi] 0.622592
           maximum_common_subgraph_distance             [invae] 0.428571
           permutation_marginalized_ssim               [scanvi] 0.745404
           persistence_diagram_distance               [harmony] 0.240177
           precision                                  [harmony] 0.464286
           random_walk_kernel_distance                 [scanvi] 0.869059
           recall                                      [scanvi] 1.000000
           spectral_distance                         [tardis_1] 0.776626
           weisfeiler_lehman_distance                    [scvi] 0.301033
embedding  branch_silhouette_score                    [harmony]      NaN
           directionality_preservation               [tardis_1] 0.209067
           embedding_distance_correlation            [tardis_1] 0.554392
           gearys_c_embedding                           [invae] 0.310606
           graph_based_trustworthiness                [harmony] 0.593224
           morans_i_embedding                            [scvi] 0.866706
           neighborhood_preservation_score            [harmony] 1.000000
           normalized_mean_curvature                    [X_pca] 0.000000
           sammons_stress                              [scanvi] 0.358587
           trajectory_cardinality_validation            [X_pca] 0.000000
           wasserstein_distance_embedding             [harmony] 0.934321
pseudotime cdf_cramer_von_mises                      [tardis_1] 0.510008
           cdf_kolmogorov_smirnov                        [scvi] 0.372304
           concordance_index                          [harmony] 0.769947
           dtw_distance                                  [scvi] 0.690785
           gearys_c_pseudotime                         [scanvi] 0.162721
           kendall_correlation                        [harmony] 0.769947
           mae                                           [scvi] 0.572890
           morans_i_pseudotime                        [harmony] 0.796446
           mse                                           [scvi] 0.490123
           mutual_information_kde                     [harmony] 0.599521
           normalized_mutual_information              [harmony] 0.740032
           pearson_correlation                        [harmony] 0.627601
           r_squared                                  [harmony] 0.701887
           r_squared_with_spline                      [harmony] 0.765092
           spearman_correlation                       [harmony] 0.865084
           wasserstein_distance_pseudotime               [scvi] 0.443432

                                              harmony    invae   scanvi  \
path       metric
adjacency  accuracy                          0.000000 1.000000 0.571429
           average_shortest_path_difference  0.000000 0.910416 1.000000
           clustering_coeff_diff             1.000000 0.360414 0.000000
           f1_score                          0.195745 1.000000 0.000000
           frobenius                         1.000000 0.000000 0.298316
           gdv_similarity                    0.000000 0.691400 0.739880
           gin_gnn_similarity                0.000000 0.876505 1.000000
           graph_edit_distance               1.000000 0.000000 0.428571
           hamming_distance                  1.000000 0.000000 0.428571
           jaccard_similarity                0.170213 1.000000 0.000000
           l1_norm                           1.000000 0.065628 0.000000
           laplacian_spectral_emd            1.000000 0.434184 0.000000
           mantel_correlation                1.000000 0.537267 0.477257
           maximum_common_subgraph_distance  1.000000 0.000000 0.428571
           permutation_marginalized_ssim     0.343460 1.000000 0.000000
           persistence_diagram_distance      0.000000 0.290751 1.000000
           precision                         0.000000 1.000000 0.722222
           random_walk_kernel_distance       1.000000 0.441714 0.000000
           recall                            1.000000 1.000000 0.000000
           spectral_distance                 1.000000 0.392929 0.137819
           weisfeiler_lehman_distance        1.000000 0.226103 0.034443
embedding  branch_silhouette_score           0.000000      NaN      NaN
           directionality_preservation       0.077976 0.681106 0.444816
           embedding_distance_correlation    0.276249 1.000000 0.841620
           gearys_c_embedding                0.456685 0.000000 0.383210
           graph_based_trustworthiness       0.000000 0.628329 1.000000
           morans_i_embedding                0.539921 1.000000 0.793081
           neighborhood_preservation_score   0.000000 0.610768 0.947935
           normalized_mean_curvature         0.023241 1.000000 0.577423
           sammons_stress                    0.512377 0.277366 0.000000
           trajectory_cardinality_validation 0.467758 0.281929 0.006533
           wasserstein_distance_embedding    0.000000 1.000000 0.486464
pseudotime cdf_cramer_von_mises              1.000000 0.309559 0.305918
           cdf_kolmogorov_smirnov            1.000000 0.153511 0.133614
           concordance_index                 0.000000 0.737361 1.000000
           dtw_distance                      1.000000 0.831165 0.704443
           gearys_c_pseudotime               1.000000 0.370026 0.000000
           kendall_correlation               0.000000 0.737361 1.000000
           mae                               1.000000 0.245124 0.482855
           morans_i_pseudotime               0.000000 0.567357 1.000000
           mse                               1.000000 0.150832 0.423153
           mutual_information_kde            0.000000 0.577025 0.939234
           normalized_mutual_information     0.000000 0.472724 1.000000
           pearson_correlation               0.000000 0.806705 0.673678
           r_squared                         0.000000 0.913133 0.769565
           r_squared_with_spline             0.000000 0.640321 1.000000
           spearman_correlation              0.000000 0.834953 1.000000
           wasserstein_distance_pseudotime   1.000000 0.167395 0.345738

                                                 scvi  tardis_1  tardis_2
path       metric
adjacency  accuracy                          0.857143  0.571429  0.571429
           average_shortest_path_difference  0.931635  0.890834  0.925810
           clustering_coeff_diff             0.243641  0.228019  0.201092
           f1_score                          0.756286  0.195745  0.195745
           frobenius                         0.383762  0.164124  0.529560
           gdv_similarity                    1.000000  0.803734  0.803734
           gin_gnn_similarity                0.947389  0.997220  0.997055
           graph_edit_distance               0.142857  0.428571  0.428571
           hamming_distance                  0.142857  0.428571  0.428571
           jaccard_similarity                0.723404  0.170213  0.170213
           l1_norm                           0.193280  0.079566  0.133934
           laplacian_spectral_emd            0.201654  0.120363  0.101506
           mantel_correlation                0.000000  0.249924  0.401614
           maximum_common_subgraph_distance  0.142857  0.428571  0.428571
           permutation_marginalized_ssim     0.526320  0.605170  0.478572
           persistence_diagram_distance      0.369500  0.455127  0.438533
           precision                         0.894180  0.619048  0.619048
           random_walk_kernel_distance       0.117638  0.025596  0.139361
           recall                            0.750000  0.250000  0.250000
           spectral_distance                 0.068670  0.000000  0.031860
           weisfeiler_lehman_distance        0.000000  0.069960  0.069960
embedding  branch_silhouette_score           1.000000  0.032494  0.271207
           directionality_preservation       0.548956  0.000000  1.000000
           embedding_distance_correlation    0.369384  0.000000  0.633266
           gearys_c_embedding                0.741330  1.000000  0.769106
           graph_based_trustworthiness       0.584394  0.561765  0.667535
           morans_i_embedding                0.000000  0.202045  0.316561
           neighborhood_preservation_score   0.444589  0.314764  0.637578
           normalized_mean_curvature         0.842211  0.484104  0.507471
           sammons_stress                    0.675351  1.000000  0.427885
           trajectory_cardinality_validation 1.000000  0.338571  0.393744
           wasserstein_distance_embedding    0.434211  0.574165  0.587919
pseudotime cdf_cramer_von_mises              0.026090  0.000000  0.170081
           cdf_kolmogorov_smirnov            0.000000  0.004793  0.021349
           concordance_index                 0.440502  0.788503  0.989988
           dtw_distance                      0.000000  0.110643  0.509378
           gearys_c_pseudotime               0.543578  0.469804  0.235396
           kendall_correlation               0.440502  0.788503  0.989988
           mae                               0.000000  0.011648  0.125344
           morans_i_pseudotime               0.135122  0.420144  0.602082
           mse                               0.000000  0.004154  0.065992
           mutual_information_kde            0.581568  0.913514  1.000000
           normalized_mutual_information     0.276762  0.360398  0.614024
           pearson_correlation               0.973620  1.000000  0.933257
           r_squared                         1.000000  0.965325  0.922602
           r_squared_with_spline             0.857158  0.895596  0.966135
           spearman_correlation              0.568460  0.859488  0.995788
           wasserstein_distance_pseudotime   0.000000  0.105377  0.181299

In [ ]:
# TODO: create a dict to indicata for which metrics lower is better for which one higher is better.
# TODO: check scib benchmarking 
# TODO: reduce the scores for each trajectory based on ranks, get trajectory ranking score
# TODO: reduce the trajectory ranking score overall.